spring:
  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true
      client:
        rest:
          auth-service:
            url: http://localhost:8080
            api:
              verify-token: /verify-token
              username-list: /username-list
        config:
          auth-serviceFeign:
            default-request-headers:
              content-type: application/json
  application:
    name: MessageService
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: C##MESSAGESERVICE
    password: root
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.OracleDialect
server:
  port: 8081
